grafana:
  persistence: { enabled: true, storageClassName: gp3, size: 2Gi }
prometheus:
  prometheusSpec:
    retention: 24h
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources: { requests: { storage: 10Gi } }
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources: { requests: { storage: 2Gi } }

    alertmanagerConfigSelector:
      matchLabels:
        securecart: enabled
