apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: securecart-observer
  namespace: securecart
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: securecart-observers
  namespace: securecart
subjects:
  - kind: Group
    name: securecart-observers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: securecart-observer
